FROM python

# Set the working directory in the container
WORKDIR /code

# Copy the requirements file and install dependencies
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire project into the container
COPY . .

# Set the environment variable for production
ENV PYTHONUNBUFFERED 1

# Command to run tests
CMD ["python", "manage.py", "test"]
